name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 24, 25-ea ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
      - name: Cache Maven artifacts
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v4
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
      - name: Build ${{ matrix.java-version }}
        id: build
        run: mvn -B clean install

      - name: Rickroll
        if: failure() && matrix.java-version == 24
        run: |
          echo "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

      - name: Télécharger le score précédent
        if: matrix.java-version == 24
        uses: dawidd6/action-download-artifact@v3
        continue-on-error: true
        with:
          name: fichierScore
          workflow: build.yml

      - name: Tests de mutation
        id: pitest
        if: matrix.java-version == 24
        run: |
          mvn org.pitest:pitest-maven:mutationCoverage -pl navigation | tee pitest.log

          nouveauScore=$(grep "mutations Killed" pitest.log | grep -o '[0-9]*%' | tr -d '%')
          if [ -z "$nouveauScore" ]; then
            echo "Aucun score trouvé."
            exit 1
          fi
          echo "Nouveau score: $nouveauScore%"
          echo "score=$nouveauScore" >> $GITHUB_OUTPUT

      - name: Comparaison des scores
        id: compare
        if: matrix.java-version == 24
        run: |
          nouveauScore=${{ steps.pitest.outputs.score }}
          echo "Score: $nouveauScore%"
          if [ ! -f fichierScore.txt ]; then
            echo "Aucun score trouvé. $nouveauScore%"
          else
            ancienScore=$(cat fichierScore.txt)
            echo "Score précédent: $OLD_SCORE%"
            if [ "$nouveauScore" -lt "$ancienScore" ]; then
              echo "Score baissé: $ancienScore% → $nouveauScore%"
              exit 1
            else
              echo " $ancienScore% → $nouveauScore%"
            fi
          fi
          echo "$nouveauScore" > fichierScore.txt

      - name: enregistrement du score
        if: success() && matrix.java-version == 24
        uses: actions/upload-artifact@v4
        with:
          name: fichierScore
          path: fichierScore.txt


