name: Build and Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build complet (sans tests)
        run: mvn -q -DskipTests install

      - name: Test
        run: mvn -q test

      - name: PIT
        run: mvn -q \
              -DargLine="" \
              -pl navigation \
              org.pitest:pitest-maven:mutationCoverage

      - name: ExtraireScore
        id: score_mutation
        run: |
          FICHIER=$(find navigation/target/pit-reports -name "mutations.xml" | head -1)
          SCORE_ACTUEL=$(grep -oP 'coverage="\K[0-9]+' "$FICHIER")
          echo "valeur=$SCORE_ACTUEL" >> $GITHUB_OUTPUT

      - name: ChargerScorePrecedent
        id: score_precedent
        run: |
          if [ -f .github/mutation_score.txt ]; then
            SCORE_OLD=$(cat .github/mutation_score.txt)
          else
            SCORE_OLD=0
          fi
          echo "valeur=$SCORE_OLD" >> $GITHUB_OUTPUT

      - name: EchouerSiBaisse
        if: ${{ steps.score_mutation.outputs.valeur < steps.score_precedent.outputs.valeur }}
        run: exit 1

      - name: MiseAJourScore
        if: ${{ steps.score_mutation.outputs.valeur >= steps.score_precedent.outputs.valeur }}
        run: |
          echo "${{ steps.score_mutation.outputs.valeur }}" > .github/mutation_score.txt

      - name: Rickroll
        if: failure()
        run: |
          echo "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
